server:
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
  security:
    user:
      name: admin
      password: 1234
  profiles:
    active: prod
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false